{% set name = "interface_meta" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: db79caf4f4cf337d55c6582f77f49c8366a9b9748579adf167ff9e50ba82985c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
    - setupmeta
  run:
    - python >=3.4

test:
  imports:
    - interface_meta
    - interface_meta.utils

about:
  home: https://github.com/matthewwardrop/interface_meta
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: '`interface_meta` provides a convenient way to expose an extensible API with enforced method signatures and consistent documentation.'
  doc_url: https://github.com/matthewwardrop/interface_meta
  dev_url: https://github.com/matthewwardrop/interface_meta

extra:
  recipe-maintainers:
    - matthewwardrop
