{% set name = "interface_meta" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6abcf78d27e695b157f44f226ff955ff766d43e8dbd6bd1d763c3e2a99beb4f2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - poetry-dynamic-versioning
    - hatchling
    - hatch-vcs
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - interface_meta
    - interface_meta.utils
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests

about:
  home: https://github.com/matthewwardrop/interface_meta
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: >-
    interface_meta provides a convenient way to expose an extensible API with
    enforced method signatures and consistent documentation.
  description: |
    interface_meta provides a convenient way to expose an extensible API with
    enforced method signatures and consistent documentation.
  doc_url: https://github.com/matthewwardrop/interface_meta
  dev_url: https://github.com/matthewwardrop/interface_meta

extra:
  recipe-maintainers:
    - matthewwardrop
