{% set name = "interface_meta" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cfd706f2c552182c31c0800a80ecdab47f77b9ed3459909037a5c092389a614b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setupmeta
  run:
    - decorator
    - funcsigs
    - python
    - six

test:
  imports:
    - interface_meta
    - interface_meta.utils

about:
  home: https://github.com/matthewwardrop/interface_meta
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: '`interface_meta` provides a convenient way to expose an extensible API with enforced method signatures and consistent documentation.'
  doc_url: https://github.com/matthewwardrop/interface_meta
  dev_url: https://github.com/matthewwardrop/interface_meta

extra:
  recipe-maintainers:
    - matthewwardrop
