{% set name = "interface_meta" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8a4493f8bdb73fb9655dcd5115bc897e207319e36c8835f39c516a2d7e9d79a1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<37]

requirements:
  host:
    - pip
    - python
    - poetry-core 1.5.1
    - poetry-dynamic-versioning
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - interface_meta
    - interface_meta.utils
  requires: 
    - pip
  commands: 
    - pip check

about:
  home: https://github.com/matthewwardrop/interface_meta
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: '`interface_meta` provides a convenient way to expose an extensible API with enforced method signatures and consistent documentation.'
  description: '`interface_meta` provides a convenient way to expose an extensible API with enforced method signatures and consistent documentation.'
  doc_url: https://github.com/matthewwardrop/interface_meta
  dev_url: https://github.com/matthewwardrop/interface_meta

extra:
  recipe-maintainers:
    - matthewwardrop
